### ISSUE TITLE
disable autoscroll in some specific apps

### ISSUE THREAD

**Issue by hrstwn** [pzmarzly/x11-input-supercharger#3]
I really like this but can I disable it in some custom app where I don't need the autoscroll like in Krita?

**Comment by pzmarzly** [comment]
I've just added this functionality to [`scroll-exclude-windows`](https://github.com/pzmarzly/x11-input-supercharger/tree/scroll-exclude-window) branch. I'm not sure if I want its configuration in `Config.toml`, so for now Krita is hardcoded. If you want to change things, see 1d6c6014bff6bd2c99909dc2fa83334aa7c2300d . Binary build: [ignore-krita.zip](https://github.com/pzmarzly/x11-input-supercharger/files/3439255/ignore-krita.zip)

Tell me if that's what you were thinking of.

**Comment by hrstwn** [comment]
Thanks so much! I will check it.
