### ISSUE TITLE
Is it possible disable middle-button click after scrolling with hold = true?

### ISSUE THREAD

**Issue by ik9999** [pzmarzly/x11-input-supercharger#4]
Is it possible disable middle-button click after scrolling with hold = true?

When you have hold = true, pressing "middle" button on stylus activates scrolling mode, but when you release the button, click event happens. Is it possible to disable this behavior?

**Comment by pzmarzly** [comment]
Hi. Thanks for being interested in my project.

> when you release the button, click event happens. Is it possible to disable this behavior?

I've never thought about that, as I had my stylus buttons unbound (I disabled all actions in system's configuration).

The issue I can see is that the program right now only sees events after they happened, so it cannot block them. I don't even know whether it would be possible to block events on X11.

However, I can think of a workaround. In the current version, when autoscroll is enabled, a small window appears to indicate where you started scrolling. If you release the button when hovering over that window, does the click event cause issues? I think the click event will be sent to that small window only.

If that helps, it'd be easy to just make that window bigger.

**Comment by ik9999** [comment]
Solved it here:

https://github.com/ik9999/x11-input-supercharger/commit/3d190bcd7e5093b30cc47c967f28cfaf9b3b041e (wacom button used for scrolling has to be disabled in xorg.conf)
